### ISSUE TITLE
Auto Adapter not working over two recyclers

### ISSUE THREAD

**Issue by prathamApp** [storix/RxDiffUtil#1]
Hello,
First of all, thank you for this help and a beautiful library. The diffutil seems to be working like a charm over some fragments where only one recycler view is attached. But it is providing some pains when working over two different recyclers and adapters. Although I have maintained the difference that you suggested, by adding a TAG when dealing with more than one recyclers, But still I am facing the issue.
I just need your help to move forward and to know what I am doing wrong.
Here is some briefing over my implementation:
1. Made two different adapters for two recycler views and made sure that they implement Swappable<>.
2. The difference is getting correctly calculated and I am getting the correct result in swapData method, but the BindViewHolder method is not getting called the number of times to size of the new list. So the previous items are getting repeated not the updated one.

If you want I can share the code. Looking forward for your quick reply.
Thanks

Attached is the link for adapter class.
https://github.com/prathamApp/PrathamDigitalNew/blob/5a05870a94b862470644af53d9dd097db8ea258c/app/src/main/java/com/pratham/prathamdigital/ui/fragment_content/RV_LevelAdapter.java#L25

and the implementation of the adaper
https://github.com/prathamApp/PrathamDigitalNew/blob/5a05870a94b862470644af53d9dd097db8ea258c/app/src/main/java/com/pratham/prathamdigital/ui/fragment_content/FragmentContent.java#L234

**Comment by stanmots** [comment]
Hi,

Sorry, but this lib is no longer maintained. I created it for the project that is now obsolete. 

There were a lot of changed to Android Platform over the last year, such as new architecture components, switching support libs to AndroidX, moving to Kotlin etc. So updating this library to the new standards will require tremendous time and effort which I cannot afford at this time.

For all new projects I recommend incorporating Kotlin's coroutines. I'm sure, Google will provide you comprehensive guides on how to use DiffUtils with coroutines.

Good luck on your development journey!

**Comment by prathamApp** [comment]
Okay Thanks buddy.
